# Site settings
title: Frisbeesport.nl
email: info@frisbeesport.nl
description: > # this means to ignore newlines until "baseurl:"
  De NFB is de sportbond voor de frisbeesport in Nederland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
logo: Logo-v1.png
search: true
locale: nl_NL
owner: frisbeesport

# Build settings
markdown: kramdown
permalink:   /:categories/:title/

sass:
  sass_dir: _sass
  style: compressed
  
gems:
  - jekyll-sitemap
    
exclude: ["log", "tmp", "package.json", "README.md", "vendor"]

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
    
prose:
  siteurl: 'http://frisbeesport.github.io/'
  relativeLinks: 'http://frisbeesport.github.io/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_sass
  metadata:
    _posts/ultimate:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "hidden"
          value: "ultimate"          
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "image.feature"
        field:
          element: "text"
          label: "Afbeelding"  
      - name: "image.credit"
        field:
          element: "text"
          label: "Afbeelding door"  
      - name: "image.wash-opacity"
        field:
          element: "number"
          label: "Afbeelding wash"            
      - name: "author"
        field:
          element: "text"
          label: "Auteur"      
    _posts/discgolf:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "hidden"
          value: "discgolf"          
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "image.feature"
        field:
          element: "text"
          label: "Afbeelding"  
      - name: "image.credit"
        field:
          element: "text"
          label: "Afbeelding door"  
      - name: "image.wash-opacity"
        field:
          element: "number"
          label: "Afbeelding wash"            
      - name: "author"
        field:
          element: "text"
          label: "Auteur"   
    _posts/organisatie:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "hidden"
          value: "organisatie"          
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "image.feature"
        field:
          element: "text"
          label: "Afbeelding"  
      - name: "image.credit"
        field:
          element: "text"
          label: "Afbeelding door"  
      - name: "image.wash-opacity"
        field:
          element: "number"
          label: "Afbeelding wash"            
      - name: "author"
        field:
          element: "text"
          label: "Auteur"   
    _posts/ultimate_community:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "hidden"
          value: "organisatie"          
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "image.feature"
        field:
          element: "text"
          label: "Afbeelding"  
      - name: "image.credit"
        field:
          element: "text"
          label: "Afbeelding door"  
      - name: "image.wash-opacity"
        field:
          element: "number"
          label: "Afbeelding wash"            
      - name: "author"
        field:
          element: "text"
          label: "Auteur"           
